name: Dependency Age Check

on:
  push

jobs:
  check-dependency-age:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml
          python -c "import toml; data = toml.load('pyproject.toml'); deps = data.get('tool', {}).get('poetry', {}).get('dependencies', {}); print('\n'.join(deps.keys()))" > dependencies.txt
          pip install -r <(python -c "import toml; data = toml.load('pyproject.toml'); deps = data.get('tool', {}).get('poetry', {}).get('dependencies', {}); print('\n'.join(f'{pkg}' for pkg in deps.keys()))")

      - name: Check dependency ages
        run: |
          echo "Dependency Age Report:" > dependency-age.txt
          while IFS= read -r package; do
            latest_version=$(pip index versions $package | grep -oP '(?<=Available versions: )[\d., ]+' | awk '{print $1}')
            release_date=$(pip show $package | grep -i "release-date" | awk '{print $2}')
            echo "$package (latest: $latest_version) - Last updated: $release_date" | tee -a dependency-age.txt
          done < dependencies.txt

      - name: Upload Dependency Age Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-age-report
          path: dependency-age.txt
