name: pre-commit

on:
  push:

permissions:
  checks: write
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: '--verbose --all-files'
